lis: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"