title: FHP
email: friendsofhagbournepool@gmail.com
fundraiser: https://www.crowdfunder.co.uk/p/friends-of-hagbourne-pool
description: Friends of Hagbourne Pool

lis: false
safe: true
incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"